import Head from 'next/head';
import Image from 'next/image';
import style from 'styles/Home.module.css';

export default function Home() {
  return (
    <div className='layout_wrapper'>
      <Head>
        <title>8 Bit GI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className='logo'>Game Informer</h1>
      </header>
      <main className={style.main}>
        <h3>Press Start</h3>
        <section className={style.boss_select}>
          <div className={style.boss_card}>
            <img
              className={style.boss_image}
              src='/alexvanaken.jpeg'
              alt='alexvanaken'
            />
            <span>alex</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/brian.jpeg'
            alt='brian'
            />
            <span>brian</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/daniel.jpeg'
            alt='daniel'
            />
            <span>daniel</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/jason.jpeg'
            alt='jason'
            />
            <span>jason</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/reiner.jpeg'
            alt='reiner'
            />
            <span>reiner</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/kim.jpeg'
            alt='kim'
            />
            <span>kim</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/lianaruppert.jpeg'
            alt='lianaruppert'
            />
            <span>liana</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/marcus.jpeg'
            alt='marcus'
            />
            <span>marcus</span>
          </div>
          <div className={style.boss_card}>
            <img
              className={style.boss_image} 
            src='/reeves.jpeg'
            alt='reeves'
            />
            <span>reeves</span>
          </div>
        </section>
      </main>
      <footer>
      <p>&copy; 2020 John Barhorst</p>
    </footer>
    </div>
  )
}
